apiVersion: v1
kind: PersistentVolume
metadata:
  name: fastapi-logs-pv-dev
  labels:
    pv: fastapi-logs-dev
spec:
  capacity:
    storage: 5Gi
  accessModes: [ReadWriteMany]
  nfs:
    server: 192.168.18.141
    path: /mnt/nfs_share/mlops/fastapi/logs/dev
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fastapi-logs-pvc-dev
  namespace: fastapi-dev
spec:
  storageClassName: ""        # Empty because NFS is directly bound
  selector:
    matchLabels:
      pv: fastapi-logs-dev
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 5Gi
