{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-sm
  labels:
    app: {{ .Release.Name }}
    release: {{ .Values.monitoring.releaseLabel | quote }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}     # Collect only within the same namespace
  selector:
    matchLabels:
      app: {{ .Release.Name }}       # Matches the service selector/labels
  endpoints:
    - port: http
      path: {{ .Values.metrics.path }}
      interval: {{ .Values.metrics.interval }}
      scrapeTimeout: {{ .Values.metrics.scrapeTimeout }}
{{- end }}
