apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-logs-storage-dev
  namespace: argocd
spec:
  project: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: fastapi-dev          # Namespace for PVC (for reference)
  source:
    repoURL: https://github.com/keonhoban/mlops-infra-gitops
    targetRevision: main
    path: ops/storage/fastapi-logs/dev
  syncPolicy:
    automated:
      prune: false                  # ❗ PV safety: prune disabled (prevent deletion)
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
