FROM python:3.10-slim

# Install system tools
RUN apt update && apt install -y curl sqlite3 git

# Install MLflow
RUN pip install mlflow[extras] scikit-learn

# Working directory
WORKDIR /mlflow

CMD ["mlflow", "server", \
     "--backend-store-uri=sqlite:///mlflow.db", \
     "--default-artifact-root=/mlflow/artifacts", \
     "--host=0.0.0.0", \
     "--port=5000", \
     "--serve-artifacts"]
