FROM apache/airflow:2.8.1-python3.10

# Set environment variables
ENV AIRFLOW_HOME=/opt/airflow

# Switch to the Airflow runtime user
USER airflow

# Install additional Python packages (mlflow, scikit-learn, pandas)
RUN pip install --no-cache-dir \
    mlflow \
    scikit-learn \
    pandas

