FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy app directory
COPY app /app/app

# Install dependencies
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade pip && \
    pip install -r /app/requirements.txt

# Run FastAPI app (uvicorn)
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
