# Executor settings
executor: KubernetesExecutor

# Image settings
images:
  airflow:
    repository: hoizz/airflow-custom  # custom image
    tag: v5-mlflow-20240712           # tag
    pullPolicy: IfNotPresent

# Fixed fernetKey secret
fernetKeySecretName: my-fernet-secret

# DAG GitSync settings (GitOps)
dags:
  gitSync:
    enabled: true
    repo: git@github.com:keonhoban/airflow-dags.git
    branch: main
    subPath: dags
    depth: 1
    wait: 10
    rev: HEAD
    sshKeySecret: airflow-git-ssh-secret

# DB integration (use external PostgreSQL)
postgresql:
  enabled: false  # disable internal Postgres

# Data
data:
  metadataSecretName: airflow-db-secret  # references base64 connection in Secret

# Airflow configuration
config:
  AIRFLOW__CORE__LOAD_EXAMPLES:
    value: "False"
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION:
    value: "False"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG:
    value: "True"

# Resource recommendations
scheduler:
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"
  extraVolumes:
    - name: aws-credentials
      secret:
        secretName: aws-credentials-secret
  extraVolumeMounts:
    - name: aws-credentials
      mountPath: /home/airflow/.aws
      readOnly: true

workers:
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"
  extraVolumes:
    - name: aws-credentials
      secret:
        secretName: aws-credentials-secret
  extraVolumeMounts:
    - name: aws-credentials
      mountPath: /home/airflow/.aws
      readOnly: true

dagProcessor:
  extraVolumes:
    - name: aws-credentials
      secret:
        secretName: aws-credentials-secret
  extraVolumeMounts:
    - name: aws-credentials
      mountPath: /home/airflow/.aws
      readOnly: true

# Ingress settings (via Ingress Controller)
ingress:
  enabled: true

  apiServer:
    enabled: true
    ingressClassName: nginx
    hosts:
      - name: airflow.local
    tls:
      enabled: false  # in production set true and integrate cert-manager

# Web UI service type
apiServer:
  service:
    type: ClusterIP  # external access via Ingress

# Logs PVC settings
logs:
  persistence:
    enabled: true
    existingClaim: airflow-logs-pvc

# (optional) Configure remote log storage (e.g., S3)
# config:
#   AIRFLOW__LOGGING__REMOTE_LOGGING: "True"
#   AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: "s3://your-bucket-name/airflow-logs"
#   AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: "aws_default"
