# envs/dev/monitoring/fastapi-dev-sm.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-dev-sm
  namespace: monitoring-dev
  labels:
    release: monitoring-dev
spec:
  namespaceSelector:
    matchNames: ["fastapi-dev"]
  selector:
    matchLabels:
      app: fastapi-dev             # Matches the service label
  endpoints:
    - port: http                   # Service port name = "http"
      path: /metrics
      interval: 15s
      scheme: http
