# envs/dev/monitoring/grafana-ds-loki.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ds-loki
  namespace: monitoring-dev
  labels:
    grafana_datasource: "1"
data:
  loki.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-dev.observability-dev.svc.cluster.local:3100
        isDefault: false
        jsonData:
          derivedFields:
            # Example: Use Tempo integration if traceID field exists
            - matcherRegex: "trace_id=(\\w+)"
              name: "traceID"
              url: "$${__value.raw}"
